version: "3.9"
   
services:
  django:
    build: ./project
    command: sh -c "gunicorn --bind 0.0.0.0:8000 volunteer.wsgi"
    volumes:
      - ./project:/project
      - static_data:/project/static
    expose:
      - 8000
    environment:
      - POSTGRES_NAME=default_db
      - POSTGRES_USER=gen_user
      - POSTGRES_PASSWORD=rokf4g6yp2
      - POSTGRES_HOST=92.255.78.119
      - TOKEN=nqVeUmakDuByuaHOTojghyKjtANCxKryYUHBThxwlyDFqVuyQwtNTCETvxeakpO

  db:
    image: postgres:13-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=H~+&-6K8X|)k01g!i?72R1eu]
      - POSTGRES_DB=django
  nginx:
    image: nginx:1.19.8-alpine
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - static_data:/var/www/html/static
      - ./nginx-conf.d:/etc/nginx/conf.d

volumes:
  pg_data:
  static_data: